// <auto-generated />
using System;
using CadastroTelefonesApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroTelefonesApi.Migrations
{
    [DbContext(typeof(CadastroTelefonesDbContext))]
    partial class CadastroTelefonesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroTelefonesApi.Model.DetalheModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                       .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bool");

                    b.HasKey("Id");

                    b.ToTable("Detalhe");
                });

            modelBuilder.Entity("CadastroTelefonesApi.Model.CadastroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<DateTime>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bool");

                    b.HasKey("Id");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("CadastroTelefonesApi.Model.DetalheModel", b =>
                {
                    b.HasOne("CadastroTelefonesApi.Model.FichaModel", "Cadastro")
                        .WithMany("Detalhe")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cadastro");
                });

            modelBuilder.Entity("CadastroTelefonesApi.Model.CadastroModel", b => b.Navigation("Detalhe"));
        }
    }
}
